# Generated by Django 6.0.5 on 2026-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('solar_kw', models.FloatField()),
                ('load_kw', models.FloatField()),
                ('grid_price_eur_per_kwh', models.FloatField()),
                ('battery_power_kw', models.FloatField(help_text='Positive = discharging, negative = charging, zero = idle')),
                ('soc_kwh', models.FloatField()),
                ('grid_import_kw', models.FloatField()),
                ('curtailed_solar_kw', models.FloatField()),
                ('charged_kwh', models.FloatField()),
                ('discharged_kwh', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('solar_kw', models.FloatField()),
                ('load_kw', models.FloatField()),
                ('grid_price_eur_per_kwh', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
