BATTERY_CAPACITY_KWH = 400.0
BATTERY_POWER_LIMIT_KW = 200.0

SOC_MIN_FRACTION = 0.10
SOC_MAX_FRACTION = 0.95

SOC_MIN_KWH = BATTERY_CAPACITY_KWH * SOC_MIN_FRACTION
SOC_MAX_KWH = BATTERY_CAPACITY_KWH * SOC_MAX_FRACTION

ROUND_TRIP_EFFICIENCY = 0.88
CHARGE_EFFICIENCY = ROUND_TRIP_EFFICIENCY ** 0.5
DISCHARGE_EFFICIENCY = ROUND_TRIP_EFFICIENCY ** 0.5

INTERVAL_HOURS = 0.25

DAY_PRICE_EUR_PER_KWH = 0.30
NIGHT_PRICE_EUR_PER_KWH = 0.15